In [ ]:
import numpy as np

a = np.array([1,3,5], dtype='int16')
print(a)

b = np.array([
    [9.0, 8.0, 7.0,],
     [6.0, 5.0, 4.0]
])

print(b)

print(a.ndim) # dimension
print(b.ndim) # "
print(b.shape) # shape
print(a.dtype) # type

print(a.size) # Get total size
print(a.nbytes)

[1 3 5]
[[9. 8. 7.]
 [6. 5. 4.]]
1
2
(2, 3)
int16
3
6


#### **Accessing/Changing specific elements, row, columns, etc**

In [ ]:
import numpy as np

a = np.array([
    [1, 2, 3, 4, 5, 6, 7, 8],
    [9,10,11,12,13,14,15,16]
])

#print(a.shape)

# Get a specific element
#print(a[1,-4])

# Get specific row
#print(a[0, :])

# Get specific column
#print(a[:, 2])

# Getting more fancy
# [startindex:endindex:stepsize]

#asd = a[:, 0:8:2]
#print(asd)
print(a)
a[0,0] = 999
print(a)
a[0,:] = 777
print(a)
a[1,:] = 369
print(a)
a[0,:] = [8, 16, 32, 64, 128, 256, 512, 1024]
print(a)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[999   2   3   4   5   6   7   8]
 [  9  10  11  12  13  14  15  16]]
[[777 777 777 777 777 777 777 777]
 [  9  10  11  12  13  14  15  16]]
[[777 777 777 777 777 777 777 777]
 [369 369 369 369 369 369 369 369]]
[[   8   16   32   64  128  256  512 1024]
 [ 369  369  369  369  369  369  369  369]]


In [ ]:
# 3d example
import numpy as np

a = np.array([
    [
        [1,2],
        [3,4],
        [6,7],
        [8,9]
    ],

    [
        [10,11],
        [12,13],
        [13,14],
        [15,16]
    ]
])


a[0,:,:] = 1222
print(a)

[[[1222 1222]
  [1222 1222]
  [1222 1222]
  [1222 1222]]

 [[  10   11]
  [  12   13]
  [  13   14]
  [  15   16]]]


In [ ]:
# Initializing Different Types of Arrays
import numpy as np

# 0s array
# print(np.zeros((5, 5, 3)))
# print("\n")

# 1s array
# b = np.ones((3,3,8), dtype='int32')
# print(b)


# any number
# c = np.full((4, 2, 4), 777)
# print(c)

#any other number
a = np.array([
    [1, 2, 3, 4, 5, 6, 7],
    [8, 9, 10, 11, 12, 13, 14]
])

# print(np.full_like(a, 4))

# Random decimal numbers
# np.random.rand(5,3)
# np.random.random_sample(a.shape)


# identity matrix
print(np.identity(6))

arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Bro Code: Learn NumPy in 1 hour!🔢
#####  https://www.youtube.com/watch?v=VXU4LSAQDSc

In [ ]:
# 00:05:07 multidimensional arrays 🧊
import numpy as np

array0 = np.array([
    [1, 2, 3, 4, 5, 6, 7, 8],
    [9, 10, 11, 12, 13, 14, 15, 16],
    [17, 18, 19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30, 31, 32]
])
print(array0)
array0 = array0*3
print(array0)
#print(np.ndim(array))


array1 = np.array([
    [['A', 'B', 'C'],
     ['D', 'E', 'F'],
     ['G', 'H', 'I']],

    [['J', 'K', 'L'],
     ['M', 'N', 'O'],
     ['P', 'Q', 'R']]
])

#print(array1)
#print(np.ndim(array1))
#print(array1.shape)

# not good: print(array1[n][n][n])
print(array1[1, 1, 2])    # good
word = array1[1, 1, 0] + array1[1, 1, 2] + array1[1, 1, 0]
word1 = array1[0, 0, 2] + array1[0,0,0] + array1[1, 2, 2]
word2 = array1[1, 2, 0] + array1[0, 1, 1] + array1[0,0,0]
print(word + " " + word1)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]
[[ 3  6  9 12 15 18 21 24]
 [27 30 33 36 39 42 45 48]
 [51 54 57 60 63 66 69 72]
 [75 78 81 84 87 90 93 96]]
O
MOM CAR


In [ ]:
# 00:12:54 slicing ✂
import numpy as np

array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])


# print(array[:,0:3])
# print(array[0:4, [0, 3]])
print(array)

array1 = array.copy()
array1[1:3, 1:3] = 0

print(array1)
print(array)
print(array[0:2, 0:2])
print(array[0:2, 2:4])
print(array[2:4, 0:2])
print(array[2:4, 2:4])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[ 9 10]
 [13 14]]
[[11 12]
 [15 16]]


In [ ]:
# 00:24:04 arithmetic ✖

# Scalar arithmetic
# array = np.array([1,2,3])
# print(array + 3)
# print(array - 2)
# print(array * 4)
# print(array ** 5)

# Vectorized math functions
# array1 = np.array([1.01, 2.5, 3.99])
# print(array1)
# print(array1)

# print(np.sqrt(array1))
# print(np.ceil(array1))
# print(np.floor(array1))
# print(np.round(array1))

# EXERCISE
# radii = np.array([1, 2, 3])
# radii = np.pi * radii ** 2
# print(radii)

# Element-wise arithmetic
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1 + array2)
print(array1 - array2)
print(np.matmul(array1, array2))
array3 = np.array([32, 5, 10])
array4 = np.array([1, 2, 8])
print(np.matmul(array3, array4))

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
32
122
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
import numpy as np
# comparison operators
scores = np.array([91, 55, 100, 73, 82, 64])

print(scores[scores >= 70])
print(scores >= 60)
print(scores < 60)
scores[scores < 60] = 0
print(scores)

[ 91 100  73  82]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  82  64]


In [ ]:
import numpy as np
# 00:33:21 broadcasting 📡
# Broadcasting allows NumPy to perform operations on arrays
# with different shapes by virtuall expanding dimensions
# so they match the larger array's shape

# The dimensions have the SAME size
# OR
# One of the dimensions has a size of 1

'''
array1 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

array2 = np.array([
    [1],
    [2],
    [3],
    [4]
])

print(array1)
print(array1.shape)
print(array2)
print(array2.shape)
print(array1 * array2)
'''

array1 = np.array([
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
])

array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1.shape)
print(array2.shape)
print(array1 * array2)


(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
# 00:39:42 aggregate functions 📊
# use aggregate functions in order to:
# summarize data and
# typically return single value

import numpy as np
array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

print(np.sum(array, axis=1))

'''
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array)) # index of min number
print(np.argmax(array)) # index of max number
'''

[15 40]


'\nprint(np.sum(array))\nprint(np.mean(array))\nprint(np.std(array))\nprint(np.min(array))\nprint(np.max(array))\nprint(np.argmin(array)) # index of min number\nprint(np.argmax(array)) # index of max number\n'

In [ ]:
# 00:43:48 filtering 🧲
import numpy as np

# Filtering = it refers to the process of selecting elements from an array
#             that match given condition/s

ages = np.array([
    [21, 17, 19, 20, 16, 30, 18, 65],
    [39, 22, 15, 99, 18, 19, 20, 21]
])

'''
mask = ages < 18
teenagers = ages[mask]
adults = ages[(ages >= 18) & (ages < 65)]
seniors = ages[ages >=65]
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]
print(ages)
print(teenagers)
print(adults)
print(seniors)
print(evens)
print(odds)
'''

adults = np.where(ages >= 18, ages, 0)
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [ ]:
# 00:52:03 random numbers 🎲
import numpy as np

# integers
rng = np.random.default_rng(seed=1) # random number generator is --rng--
print(rng.integers(1, 7))
print(rng.integers(1, 7, size=(16, 32)))

# floating number 0 - 1
print(np.random.uniform(low=-999, high=999))

asd = np.random.uniform(low=-999, high=999, size= 256)
print(asd)

3
[[4 5 6 1 1 5 6 2 2 6 3 2 5 2 3 4 4 1 1 6 5 6 4 5 2 3 5 1 2 1 3 6]
 [1 3 3 6 2 4 2 1 5 1 2 3 3 1 6 5 6 1 5 2 4 6 2 5 1 2 6 3 4 2 1 3]
 [4 3 5 3 4 5 6 3 1 5 4 6 3 3 1 3 4 5 6 2 4 5 2 3 6 4 4 5 4 6 5 1]
 [1 4 5 1 5 5 5 6 2 4 5 3 2 3 1 2 6 5 6 6 6 2 3 4 2 6 1 6 4 2 5 3]
 [6 6 2 3 2 5 4 6 5 6 6 6 1 1 3 3 6 5 3 4 4 6 1 3 5 3 6 6 5 3 6 1]
 [4 2 2 5 5 6 2 6 5 2 1 5 5 3 1 1 3 5 2 1 5 5 2 4 3 4 1 4 2 4 3 4]
 [1 3 4 5 3 1 5 4 4 1 3 6 6 2 4 1 5 2 3 6 4 6 2 5 6 1 2 1 2 2 1 6]
 [2 6 5 2 5 5 1 1 3 1 3 3 4 4 3 2 4 3 6 5 5 4 3 2 3 4 3 1 1 1 2 3]
 [2 2 2 5 2 6 4 1 6 6 5 1 5 5 5 5 4 3 6 6 5 3 4 4 1 1 3 4 2 2 1 6]
 [4 2 5 6 2 6 5 5 4 6 1 1 6 3 3 5 2 4 6 5 1 6 5 5 2 6 3 6 2 1 6 4]
 [3 6 6 1 4 5 5 4 4 4 2 1 3 5 6 6 2 1 6 5 5 5 3 6 4 4 3 3 3 5 4 1]
 [1 2 3 4 6 5 2 4 5 6 3 5 2 3 6 3 1 5 2 3 6 3 2 2 6 2 4 2 5 5 4 3]
 [3 6 5 3 1 1 3 3 3 6 3 5 1 3 2 1 4 1 3 5 5 4 4 2 6 2 5 1 4 2 2 3]
 [5 5 2 4 1 6 6 3 4 4 5 1 4 6 4 4 1 6 2 3 5 3 4 4 1 1 6 5 1 5 4 5]
 [1 5 5 6 2 3 1 1 1 3 2 5 2 4 4 2 3 6 6 2 6 2 5 3 5 4 6 3 6 

In [ ]:
print("DÍA 3 - NUMPY 100% CERRADO")
print("="*50)
np.random.seed(42) # la semilla (como en el minecraft)
print("Mi primer 'modelo' generativo (fake):")
for i in range(10):
    print(np.random.randint(1, 7), end=" ")  # tirando dados como un transformer

DÍA 3 - NUMPY 100% CERRADO
Mi primer 'modelo' generativo (fake):
4 5 3 5 5 2 3 3 3 5 